steps:
  - name: 'maven:3.9-amazoncorretto-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-e', '-X']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shelfie-425209/shelfie:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shelfie-425209/shelfie:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'shelfie', '--image', 'gcr.io/shelfie-425209/shelfie:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--update-env-vars', 'SPRING_PROFILES_ACTIVE=production', '--verbosity', 'debug', '--set-secrets', 'SECRET_DB_PW=shelfie-postgres-pw:latest,SECRET_ADMIN_PW=shelfie-admin-pw:latest']
